spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  docker:
    compose:
      enabled: false
  main:
    banner-mode: off
  output:
    ansi:
      enabled: never

app:
  jwt:
    secret: ${JWT_SECRET:e28361eb-4e21-4632-bc37-9937b7c5c56d}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
    include-message: never
  compression:
    enabled: true
